projectName: cameroon-iol-on-platform
image: jembi/platform:latest
logPath: /tmp/logs

packages:
    - cameroon-iol-on-platform

customPackages:
    - id: cameroon-iol-on-platform
      path: ../cameroon-iol-on-platform

profiles:
    - name: dev
      packages:
        - cameroon-iol-on-platform
      envFiles:
        - ./.env.local
      dev: true
      only: false

    - name: qa
      packages:
        - cameroon-iol-on-platform
        - reverse-proxy-nginx
      envFiles:
        - ./.env.qa
      dev: false