version: '3.9'

services:
  json-mapper:
    image: jembi/json-mapper-service
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: $DATA_DIR_INPUT/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: $DATA_DIR_INPUT/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:


  notification-service:
    image: jembi/notification-service
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: ${DATA_DIR_NOTIFICATIONS}/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: ${DATA_DIR_NOTIFICATIONS}/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:

  dispatcher-service:
    image: jembi/dhis2-exporter-service:latest
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: ${DATA_DIR_DISPATCH}/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: ${DATA_DIR_DISPATCH}/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:

  metadata-service:
    image: jembi/report-metadata-service:latest
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: ${DATA_DIR_METADATA}/metadata
        target: /app/metadata
        read_only: false
      - type: bind
        source: ${DATA_DIR_METADATA}/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: ${DATA_DIR_METADATA}/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:
      default:

  cameroon-iol-ui:
    image: jembi/cameroon-iol-ui:latest
    
    networks:
      reverse-proxy:
      openhim:
      default:
      

networks:
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  openhim: 
    name: openhim_public
    external: true
  kafka:
    name: kafka_public
    external: true
  default:
