version: '3.9'

services:
  json-mapper:
    image: jembi/json-mapper-service
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/input/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/input/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:


  notification-service:
    image: jembi/notification-service
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/notifications/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/notifications/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:

  dispatcher-service:
    image: jembi/dhis2-exporter-service:latest
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/dispatch/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/dispatch/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:

  metadata-service:
    image: jembi/report-metadata-service:latest
    environment:
      KAFKA_HOSTS: ${KAFKA_HOSTS}
    deploy:
    volumes:
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/metadata/metadata
        target: /app/metadata
        read_only: false
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/metadata/logs
        target: /app/logs
        read_only: false
      - type: bind
        source: /home/ubuntu/ciol_docker_data/data-apps/metadata/conf
        target: /app/conf
        read_only: false
    networks:
      openhim:
      kafka:

networks:
  openhim: 
    name: openhim_public
    external: true
  kafka:
    name: kafka_public
    external: true
